name: Update References

on:
  workflow_dispatch:
  schedule:
    # Bi-weekly
    - cron: "0 0 1-7,15-21 * 0"
  push:
    paths:
      - .github/workflows/update-references.yml
      - data/generate-references.sh
      - data/references.yml

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update references
      run: |
        # Ensure comments are present
        grep -Pzq '<!-- references:start -->(\n|.)*<!-- references:end -->' README.md
        # Get content
        content=$(./data/generate-references.sh)
        # Replace content within comments with generated data
        awk -v content="$content" -i inplace '
            BEGIN {p=1}
            /^<!-- references:start -->/{print content;p=0}
            /^<!-- references:end -->/{p=1}
            p' README.md

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update references
